site_name: Socrates site
author: Honza
posts_per_page: 0
url: https://honza.ca
date_format: "%B %d, %Y"
text_processor: extension
templates: jinja2
append_slash: false
url_include_day: false
initial_header_level: 1
punctuation: true
ligatures: false
deploy_dir: "../"
