name = "Contrast"
license = "public domain"
licenselink = "https://github.com/niklasbuschmann/contrast-hugo/blob/master/LICENSE.txt"
description = "Minimalistic Hugo theme"
homepage = "https://github.com/niklasbuschmann/contrast-hugo"
tags = ["blog"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "Niklas Buschmann"
  homepage = "https://github.com/niklasbuschmann/"
